services:
  db:
    image: postgres:16
    container_name: agendazap-db
    environment:
      POSTGRES_DB: agendazap
      POSTGRES_USER: agendazap
      POSTGRES_PASSWORD: agendazap
    ports:
      - "5432:5432"
    volumes:
      - agendazap_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: agendazap-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  agendazap_db:
